@Kromer_HostAddress = http://localhost:5241

GET {{Kromer_HostAddress}}/weatherforecast/
Accept: application/json

###

# same address returned
POST {{Kromer_HostAddress}}/api/krist/login
#POST https://kromer.reconnected.cc/api/krist/login
Accept: application/json
Content-Type: application/json

{
    "privatekey": "1234"
}

###

GET {{Kromer_HostAddress}}/api/krist/motd

###

#POST {{Kromer_HostAddress}}/api/krist/v2
#POST https://kromer.reconnected.cc/api/krist/login
POST https://krist.dev/v2
Accept: application/json
Content-Type: application/json

{
  "privatekey": "1234"
}
